### ISSUE TITLE
High Throughput lossy encoding is broken

### ISSUE THREAD

**Issue by DAOCUONG** [GrokImageCompression/grok#254] opened 2021-07-25 18:05 UTC
Tried examples : Doesnt work not sure why 
grk_compress -i @INPUT_NR_PATH@/Bretagne2.jpg -o @TEMP_PATH@/Bretagne2_ht.j2k -M 64
grk_compress -i @INPUT_NR_PATH@/Bretagne2.jpg -o @TEMP_PATH@/Bretagne2_ht_lossy.j2k -M 64 -I
grk_compress -i @INPUT_NR_PATH@/Bretagne2.jpg -o @TEMP_PATH@/Bretagne2_ht_lossy_plt.j2k -M 64 -I -PLT

**Comment by DAOCUONG** [comment] 2021-07-25 18:08
Tried to use jpeg image out put just grey image

**Comment by boxerab** [comment] 2021-07-25 20:47
You need to have a valid path to an image.
`@INPUT_NR_PATH@/Bretagne2.jpg` is not valid.

**Comment by DAOCUONG** [comment] 2021-07-25 23:32
I have did that with my jpg picture but it doesnt work . I use mac and install through brew

**Comment by DAOCUONG** [comment] 2021-07-25 23:33
Above is just example of command that i used

**Comment by DAOCUONG** [comment] 2021-07-25 23:34
@boxerab

**Comment by DAOCUONG** [comment] 2021-07-26 04:40
I got it work mac cant not view j2k or j2c need to use grok decompress back to jpg to test

**Comment by boxerab** [comment] 2021-07-26 13:07
@DAOCUONG glad to hear you got it working. I'm afraid there is no viewer at the moment
that can view HTJ2K images.

**Comment by DAOCUONG** [comment] 2021-07-26 18:26
@boxerab i got first comnand working but not (tried to pass option to decrease the size of out put file)
grk_compress -i @INPUT_NR_PATH@/Bretagne2.jpg -o @TEMP_PATH@/Bretagne2_ht_lossy.j2k -M 64 -I
grk_compress -i @INPUT_NR_PATH@/Bretagne2.jpg -o @TEMP_PATH@/Bretagne2_ht_lossy_plt.j2k -M 64 -I -PLT

Above 2 comamnds doesnt work for ppm as well as jpg. Is any option i can tried to reduce the size of high through put mode but has smaller size for output file ? Thanks so much

**Comment by boxerab** [comment] 2021-07-26 22:17
> Above 2 commands doesnt work for ppm as well as jpg.

To fix this problem, please post the output from the command when it doesn't work. You can add a `-v` option to get verbose output. 

Also, you can find some options to set the compression ratio [here](https://github.com/GrokImageCompression/grok/wiki/3.-grk_compress). For example, adding  `-r 20` to the command line will give you 20 times compression.

**Comment by DAOCUONG** [comment] 2021-07-27 00:31
First command 
grk_compress -i lab.jpg -o lab.j2k  -M 64 -v
[2021-07-26 19:23:22.359] [info] compress time: 82.617287 ms

out put file size bigger than input file, i want the out put smaller than input size 
-rw-r--r--  1 dao  staff  496746 Jul 26 19:23 lab.j2k
-rw-r--r--  1 dao  staff  190640 Jul 14 14:27 lab.jpg

When we decode lab.j2k to decode.jpg we can view jpg file like the original one 
============================================================
Second Command 
grk_compress -i lab.jpg -o lab.j2k -M 64 -I -v
[2021-07-26 19:24:40.975] [info] compress time: 83.511002 ms

ls -l
-rw-r--r--  1 dao  staff   15338 Jul 26 19:24 lab.j2k
-rw-r--r--  1 dao  staff  190640 Jul 14 14:27 lab.jpg

decode out put file back to original 
 grk_decompress -i lab.j2k -o decode.jpg -v 
[2021-07-26 19:26:34.305] [info] decompress time: 56.205974999999995 ms

decode.jpg is grey image not look like the original one 

===========================================
Third Command 
grk_compress -i lab.jpg -o lab.j2k -M 64 -I -PLT -v
[2021-07-26 19:28:50.488] [info] compress time: 81.516362 ms
ls -l
-rw-r--r--  1 dao  staff   15370 Jul 26 19:28 lab.j2k
-rw-r--r--  1 dao  staff  190640 Jul 14 14:27 lab.jpg

decode out put file back to original 
 grk_decompress -i lab.j2k -o decode.jpg -v 
[2021-07-26 19:26:34.305] [info] decompress time: 56.205974999999995 ms

decode.jpg is grey image not look like the original one 
=========================================== 

HT mean can compress faster but the size should smaller than original one i still dont know 
tried this 
grk_compress -i lab.jpg -o lab.j2k -M 64 -r 20 -v
we have error
[2021-07-26 19:30:46.271] [error] failed to compress image: grk_compress
[2021-07-26 19:30:46.273] [error] failed to compress image

**Comment by boxerab** [comment] 2021-07-27 01:06
@DAOCUONG please share the lab.jpg file, if you can. Then we can find out what is wrong.

**Comment by boxerab** [comment] 2021-07-27 01:11
`grk_compress -i lab.jpg -o lab.j2k -M 64 -v`

This command takes a lossy-compressed file, decompresses it, and then performs **lossless** compression. So, the output may be larger than the input file. This is normal.

**Comment by DAOCUONG** [comment] 2021-07-27 01:53
![lab](https://user-images.githubusercontent.com/5289711/127082436-3a78adf1-bdc7-49b3-8388-a0a3e8df26b9.jpg)

**Comment by DAOCUONG** [comment] 2021-07-27 01:54
@boxerab i tried without HT mode the file still bigger with -r 20

**Comment by boxerab** [comment] 2021-07-28 15:20
The issue with blank output for lossy HTJ2K has been fixed in master. This will not be available on brew until the next release.

As for transcoded file bigger than original, this is not a bug - lossless output or output with low compression ratio will always be larger than original image if original image has high compression ratio.

**Closed by boxerab** 2021-07-28 15:20 UTC
